/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.example;

import net.example.common.*;
import net.example.connection.*;
import net.example.model.*;
import net.example.dao.*;

public class App {
    public static void main(String[] args) {

        try {

            UserDAO userDao = new UserDAO();

            userDao.deleteAll();

            User user= new User();

            user.setUser_id("test");
            user.setPass_wd("12345");
            user.setAge(15);
            user.setName("p");
            
            userDao.mixAddAndUpdate(user);
            
        } catch(Exception e) {
            e.printStackTrace();
        }
    }



}
