/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.example;

import org.testng.annotations.*;
import static org.testng.Assert.*;

public class AppTest {
    @Test 
    public void appHasAGreeting() {
    }
}
